package de.jlnstrk.transit.client.hci.model

import de.jlnstrk.transit.client.hafas.HciModel
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@HciModel("1.45")
@Serializable
public enum class HciExtension {
  _EMPTY_,
  @SerialName("ARRIVA.1")
  ARRIVA_1,
  @SerialName("AUSTIN.1")
  AUSTIN_1,
  @SerialName("AVV.AACHEN.1")
  AVV_AACHEN_1,
  @SerialName("BENE.1")
  BENE_1,
  @SerialName("BVG.1")
  BVG_1,
  @SerialName("DB-UK-WEBTIS.1")
  DB_UK_WEBTIS_1,
  @SerialName("DB.R15.04.a")
  DB_R_15_04_A,
  @SerialName("DB.R15.06.a")
  DB_R_15_06_A,
  @SerialName("DB.R15.12.a")
  DB_R_15_12_A,
  @SerialName("DB.R15.12.b")
  DB_R_15_12_B,
  @SerialName("DB.R16.06.a")
  DB_R_16_06_A,
  @SerialName("DB.R16.08.a")
  DB_R_16_08_A,
  @SerialName("DB.R16.10.a")
  DB_R_16_10_A,
  @SerialName("DB.R16.12.a")
  DB_R_16_12_A,
  @SerialName("DB.R17.08.a")
  DB_R_17_08_A,
  @SerialName("DB.R17.10.a")
  DB_R_17_10_A,
  @SerialName("DB.R18.04.a")
  DB_R_18_04_A,
  @SerialName("DB.R18.04.b")
  DB_R_18_04_B,
  @SerialName("DB.R18.06.a")
  DB_R_18_06_A,
  @SerialName("DB.R18.06.b")
  DB_R_18_06_B,
  @SerialName("DB.R19.04.a")
  DB_R_19_04_A,
  @SerialName("DB.R19.06.a")
  DB_R_19_06_A,
  @SerialName("DB.R19.12.a")
  DB_R_19_12_A,
  @SerialName("DB.REGIO.1")
  DB_REGIO_1,
  @SerialName("DB.VD.1")
  DB_VD_1,
  @SerialName("DB.VD.2")
  DB_VD_2,
  @SerialName("DB.VD.3")
  DB_VD_3,
  @SerialName("DB.VD.4")
  DB_VD_4,
  @SerialName("DB.VD.5")
  DB_VD_5,
  @SerialName("DB.VD.6")
  DB_VD_6,
  @SerialName("DBNETZZUGRADAR.1")
  DBNETZZUGRADAR_1,
  @SerialName("DBNETZZUGRADAR.2")
  DBNETZZUGRADAR_2,
  @SerialName("DIMIS.1")
  DIMIS_1,
  @SerialName("DK.1")
  DK_1,
  @SerialName("DK.10")
  DK_10,
  @SerialName("DK.2")
  DK_2,
  @SerialName("DK.3")
  DK_3,
  @SerialName("DK.4")
  DK_4,
  @SerialName("DK.5")
  DK_5,
  @SerialName("DK.6")
  DK_6,
  @SerialName("DK.7")
  DK_7,
  @SerialName("DK.8")
  DK_8,
  @SerialName("DK.9")
  DK_9,
  @SerialName("DUBAI.1")
  DUBAI_1,
  @SerialName("DUBAI.2")
  DUBAI_2,
  @SerialName("DYNAMO.1")
  DYNAMO_1,
  @SerialName("EMMA.1")
  EMMA_1,
  @SerialName("EOS.1")
  EOS_1,
  @SerialName("HAPAG.1")
  HAPAG_1,
  @SerialName("HAPP.1")
  HAPP_1,
  @SerialName("HCI.EXP")
  HCI_EXP,
  @SerialName("HCI.RC")
  HCI_RC,
  @SerialName("HCSS.1.10")
  HCSS_1_10,
  @SerialName("HCSS.1.11")
  HCSS_1_11,
  @SerialName("HCSS.1.9")
  HCSS_1_9,
  @SerialName("HVV.1")
  HVV_1,
  @SerialName("INNO.16")
  INNO_16,
  @SerialName("INNO.20")
  INNO_20,
  @SerialName("IR.1")
  IR_1,
  @SerialName("JAVA.API.1")
  JAVA_API_1,
  @SerialName("JAVA.API.2")
  JAVA_API_2,
  @SerialName("JAVA.API.3")
  JAVA_API_3,
  @SerialName("JAVA.API.4")
  JAVA_API_4,
  @SerialName("LOGMOBILE.1")
  LOGMOBILE_1,
  @SerialName("LOROL.1")
  LOROL_1,
  @SerialName("MMILUX.1")
  MMILUX_1,
  @SerialName("MMILUX.2")
  MMILUX_2,
  @SerialName("MMILUX.3")
  MMILUX_3,
  @SerialName("MMILUX.4")
  MMILUX_4,
  @SerialName("MMILUX.5")
  MMILUX_5,
  @SerialName("MMILUX.6")
  MMILUX_6,
  MOOBILPLUS,
  @SerialName("NASA.1")
  NASA_1,
  @SerialName("NASA.2")
  NASA_2,
  @SerialName("NASA.3")
  NASA_3,
  @SerialName("NASA.4")
  NASA_4,
  @SerialName("NOKIA.1")
  NOKIA_1,
  @SerialName("NSB.1")
  NSB_1,
  @SerialName("NT.1")
  NT_1,
  @SerialName("NT.2")
  NT_2,
  @SerialName("NT.3")
  NT_3,
  @SerialName("NVV.6.0")
  NVV_6_0,
  @SerialName("OEBB.1")
  OEBB_1,
  @SerialName("OEBB.2")
  OEBB_2,
  @SerialName("OEBB.3")
  OEBB_3,
  @SerialName("OEBB.4")
  OEBB_4,
  @SerialName("OEBB.5")
  OEBB_5,
  @SerialName("OEBB.6")
  OEBB_6,
  @SerialName("OEBB.7")
  OEBB_7,
  @SerialName("POSTAUTO.1")
  POSTAUTO_1,
  @SerialName("POSTAUTO.2")
  POSTAUTO_2,
  @SerialName("POSTAUTO.3")
  POSTAUTO_3,
  @SerialName("POSTAUTO.4")
  POSTAUTO_4,
  @SerialName("POSTAUTO.5")
  POSTAUTO_5,
  @SerialName("POSTAUTO.6")
  POSTAUTO_6,
  @SerialName("POSTAUTO.7")
  POSTAUTO_7,
  @SerialName("POSTAUTO.8")
  POSTAUTO_8,
  @SerialName("POSTAUTO.9")
  POSTAUTO_9,
  @SerialName("RMV.1")
  RMV_1,
  @SerialName("RMV.2")
  RMV_2,
  @SerialName("RMV.3")
  RMV_3,
  @SerialName("RMV.4")
  RMV_4,
  @SerialName("RMV.5")
  RMV_5,
  @SerialName("RMV.6")
  RMV_6,
  @SerialName("RMV.7")
  RMV_7,
  @SerialName("RMV.8")
  RMV_8,
  @SerialName("RMV.9")
  RMV_9,
  @SerialName("S2R.1")
  S_2_R_1,
  @SerialName("SAM.3.0")
  SAM_3_0,
  @SerialName("SBB.1")
  SBB_1,
  @SerialName("SBB.10")
  SBB_10,
  @SerialName("SBB.11")
  SBB_11,
  @SerialName("SBB.12")
  SBB_12,
  @SerialName("SBB.13")
  SBB_13,
  @SerialName("SBB.14")
  SBB_14,
  @SerialName("SBB.15")
  SBB_15,
  @SerialName("SBB.16")
  SBB_16,
  @SerialName("SBB.17")
  SBB_17,
  @SerialName("SBB.18")
  SBB_18,
  @SerialName("SBB.19")
  SBB_19,
  @SerialName("SBB.2")
  SBB_2,
  @SerialName("SBB.20")
  SBB_20,
  @SerialName("SBB.21")
  SBB_21,
  @SerialName("SBB.3")
  SBB_3,
  @SerialName("SBB.4")
  SBB_4,
  @SerialName("SBB.5")
  SBB_5,
  @SerialName("SBB.6")
  SBB_6,
  @SerialName("SBB.7")
  SBB_7,
  @SerialName("SBB.8")
  SBB_8,
  @SerialName("SBB.9")
  SBB_9,
  @SerialName("SBB.TZT.1")
  SBB_TZT_1,
  @SerialName("SBB.ZPS.1")
  SBB_ZPS_1,
  @SerialName("SITKOL.1")
  SITKOL_1,
  @SerialName("SMARTRBL.ZAM.1.18")
  SMARTRBL_ZAM_1_18,
  @SerialName("SMARTVMS.1")
  SMARTVMS_1,
  @SerialName("SNCB.1")
  SNCB_1,
  @SerialName("SNCB.2")
  SNCB_2,
  @SerialName("SNCF.1")
  SNCF_1,
  @SerialName("SWITCHH.1")
  SWITCHH_1,
  @SerialName("UK.TTL.1")
  UK_TTL_1,
  @SerialName("UK.TTL.2")
  UK_TTL_2,
  @SerialName("VAO.1")
  VAO_1,
  @SerialName("VAO.10")
  VAO_10,
  @SerialName("VAO.11")
  VAO_11,
  @SerialName("VAO.12")
  VAO_12,
  @SerialName("VAO.13")
  VAO_13,
  @SerialName("VAO.2")
  VAO_2,
  @SerialName("VAO.3")
  VAO_3,
  @SerialName("VAO.4")
  VAO_4,
  @SerialName("VAO.5")
  VAO_5,
  @SerialName("VAO.6")
  VAO_6,
  @SerialName("VAO.7")
  VAO_7,
  @SerialName("VAO.8")
  VAO_8,
  @SerialName("VAO.9")
  VAO_9,
  @SerialName("VBB.1")
  VBB_1,
  @SerialName("VBB.2")
  VBB_2,
  @SerialName("VBB.3")
  VBB_3,
  @SerialName("VBB.4")
  VBB_4,
  @SerialName("VBB.5")
  VBB_5,
  @SerialName("VBN.1")
  VBN_1,
  @SerialName("VBN.2")
  VBN_2,
  @SerialName("VBN.3")
  VBN_3,
  @SerialName("VBN.4")
  VBN_4,
  @SerialName("VBN.5")
  VBN_5,
  @SerialName("VOR.1")
  VOR_1,
  @SerialName("VRR.1")
  VRR_1,
  @SerialName("WEBAPP.1")
  WEBAPP_1,
  @SerialName("ZVV.1")
  ZVV_1,
  @SerialName("ZVV.2")
  ZVV_2,
  @SerialName("ZVV.3")
  ZVV_3,
}
