package de.jlnstrk.transit.client.hci.model

import de.jlnstrk.transit.client.hafas.HciModel
import kotlinx.serialization.Serializable

@HciModel("1.45")
@Serializable
public enum class HciReferencedJourneyType {
  DEFAULT,
  DEFAULT_R,
  HAT_ENTLASTUNG,
  HAT_ERSATZFAHRT,
  HAT_FORTFUEHRUNG,
  HAT_FORTFUEHRUNG_DURCH_ZUSAMMENFUEHRUNG,
  HAT_FORTFUEHRUNG_VON_TRENNUNG,
  HAT_TRENNUNG,
  HAT_VERSTAERKERFAHRT,
  HAT_ZUSAMMENFUEHRUNG,
  IST_ENTLASTUNG,
  IST_ERSATZFAHRT,
  IST_FORTFUEHRUNG,
  IST_FORTFUEHRUNG_DURCH_ZUSAMMENFUEHRUNG,
  IST_FORTFUEHRUNG_VON_TRENNUNG,
  IST_TRENNUNG,
  IST_VERSTAERKERFAHRT,
  IST_ZUSAMMENFUEHRUNG,
  UNDEF,
}
