package de.jlnstrk.transit.client.hci.model

import de.jlnstrk.transit.client.hafas.HciModel
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@HciModel("1.45")
@Serializable
public enum class HciServiceMethod {
  @SerialName("BookingAssortment")
  BOOKING_ASSORTMENT,
  @SerialName("BookingData")
  BOOKING_DATA,
  @SerialName("BookingValidation")
  BOOKING_VALIDATION,
  @SerialName("ChatMessageSearch")
  CHAT_MESSAGE_SEARCH,
  @SerialName("ChatMessageStore")
  CHAT_MESSAGE_STORE,
  @SerialName("CheckInJourneySearch")
  CHECK_IN_JOURNEY_SEARCH,
  @SerialName("CheckInJourneyStore")
  CHECK_IN_JOURNEY_STORE,
  @SerialName("CheckInLocationSearch")
  CHECK_IN_LOCATION_SEARCH,
  @SerialName("CheckInLocationStore")
  CHECK_IN_LOCATION_STORE,
  @SerialName("CheckInTripSearch")
  CHECK_IN_TRIP_SEARCH,
  @SerialName("CheckInTripStore")
  CHECK_IN_TRIP_STORE,
  @SerialName("EventLocGeoPos")
  EVENT_LOC_GEO_POS,
  @SerialName("FeedbackMail")
  FEEDBACK_MAIL,
  @SerialName("FeedbackSearch")
  FEEDBACK_SEARCH,
  @SerialName("FeedbackStore")
  FEEDBACK_STORE,
  @SerialName("FeederBoard")
  FEEDER_BOARD,
  @SerialName("FetcherBoard")
  FETCHER_BOARD,
  @SerialName("GeoFeatureDetails")
  GEO_FEATURE_DETAILS,
  @SerialName("GeoFeatureGeoPos")
  GEO_FEATURE_GEO_POS,
  @SerialName("GisRoute")
  GIS_ROUTE,
  @SerialName("GisSearch")
  GIS_SEARCH,
  @SerialName("GraphGeoPos")
  GRAPH_GEO_POS,
  @SerialName("HimAffect")
  HIM_AFFECT,
  @SerialName("HimDetails")
  HIM_DETAILS,
  @SerialName("HimGeoPos")
  HIM_GEO_POS,
  @SerialName("HimMatch")
  HIM_MATCH,
  @SerialName("HimSearch")
  HIM_SEARCH,
  @SerialName("JourneyCourse")
  JOURNEY_COURSE,
  @SerialName("JourneyDetails")
  JOURNEY_DETAILS,
  @SerialName("JourneyGeoPos")
  JOURNEY_GEO_POS,
  @SerialName("JourneyGraph")
  JOURNEY_GRAPH,
  @SerialName("JourneyMatch")
  JOURNEY_MATCH,
  @SerialName("JourneyStructGraphPos")
  JOURNEY_STRUCT_GRAPH_POS,
  @SerialName("JourneyTrackMatch")
  JOURNEY_TRACK_MATCH,
  @SerialName("JourneyTree")
  JOURNEY_TREE,
  @SerialName("LineDetails")
  LINE_DETAILS,
  @SerialName("LineGeoPos")
  LINE_GEO_POS,
  @SerialName("LineMatch")
  LINE_MATCH,
  @SerialName("LineSearch")
  LINE_SEARCH,
  @SerialName("LocDetails")
  LOC_DETAILS,
  @SerialName("LocGeoPos")
  LOC_GEO_POS,
  @SerialName("LocGeoReach")
  LOC_GEO_REACH,
  @SerialName("LocGraph")
  LOC_GRAPH,
  @SerialName("LocMatch")
  LOC_MATCH,
  @SerialName("LocSearch")
  LOC_SEARCH,
  @SerialName("LocWalkDetails")
  LOC_WALK_DETAILS,
  @SerialName("LocWalkSearch")
  LOC_WALK_SEARCH,
  @SerialName("MatchMe")
  MATCH_ME,
  @SerialName("NotificationSearch")
  NOTIFICATION_SEARCH,
  @SerialName("NotificationStore")
  NOTIFICATION_STORE,
  @SerialName("OneFieldSearch")
  ONE_FIELD_SEARCH,
  @SerialName("PartialSearch")
  PARTIAL_SEARCH,
  @SerialName("RatingSearch")
  RATING_SEARCH,
  @SerialName("RatingStore")
  RATING_STORE,
  @SerialName("Reconstruction")
  RECONSTRUCTION,
  @SerialName("ReconstructionContextConverter")
  RECONSTRUCTION_CONTEXT_CONVERTER,
  @SerialName("SearchOnTrip")
  SEARCH_ON_TRIP,
  @SerialName("ServerInfo")
  SERVER_INFO,
  @SerialName("ShareLocation")
  SHARE_LOCATION,
  @SerialName("ShareTrip")
  SHARE_TRIP,
  @SerialName("StationBoard")
  STATION_BOARD,
  @SerialName("StructGraph")
  STRUCT_GRAPH,
  @SerialName("SubscrChannelConfirm")
  SUBSCR_CHANNEL_CONFIRM,
  @SerialName("SubscrChannelCreate")
  SUBSCR_CHANNEL_CREATE,
  @SerialName("SubscrChannelDelete")
  SUBSCR_CHANNEL_DELETE,
  @SerialName("SubscrChannelSendDetails")
  SUBSCR_CHANNEL_SEND_DETAILS,
  @SerialName("SubscrChannelUpdate")
  SUBSCR_CHANNEL_UPDATE,
  @SerialName("SubscrCreate")
  SUBSCR_CREATE,
  @SerialName("SubscrDelete")
  SUBSCR_DELETE,
  @SerialName("SubscrDetails")
  SUBSCR_DETAILS,
  @SerialName("SubscrNotification")
  SUBSCR_NOTIFICATION,
  @SerialName("SubscrSearch")
  SUBSCR_SEARCH,
  @SerialName("SubscrStatus")
  SUBSCR_STATUS,
  @SerialName("SubscrUpdate")
  SUBSCR_UPDATE,
  @SerialName("SubscrUserCreate")
  SUBSCR_USER_CREATE,
  @SerialName("SubscrUserDelete")
  SUBSCR_USER_DELETE,
  @SerialName("SubscrUserDetails")
  SUBSCR_USER_DETAILS,
  @SerialName("SubscrUserUpdate")
  SUBSCR_USER_UPDATE,
  @SerialName("SubscrValidate")
  SUBSCR_VALIDATE,
  @SerialName("TariffSearch")
  TARIFF_SEARCH,
  @SerialName("TripSearch")
  TRIP_SEARCH,
  @SerialName("UserLogin")
  USER_LOGIN,
  @SerialName("UserSearch")
  USER_SEARCH,
  @SerialName("UserStore")
  USER_STORE,
}
