package de.jlnstrk.transit.client.hci.model

import de.jlnstrk.transit.client.hafas.HciModel
import kotlinx.serialization.Serializable

@HciModel("1.45")
@Serializable
public enum class HciSOTMode {
  AT_CHANGE_STOP,
  AT_CORRECTION_POINT,
  AT_DESTINATION,
  AT_LAST_USABLE_STOP,
  AT_PASSED_STOP,
  BEFORE_TRAVEL,
  CHECK_COMPLETE_TRAIN,
  ERROR,
  ERROR_ALL_TRAINS_FILTERED,
  ERROR_IN_RECONSTRUCTION,
  ERROR_SEARCH_FROM_TRAIN_AT_DESTINATION,
  ERROR_SEARCH_FROM_TRAIN_BEFORE_START,
  ERROR_SEARCH_FROM_TRAIN_NO_TIME_AT_ARRIVAL_STATION,
  ERROR_STAY_IN_CURRENT_CONNECTION,
  ERROR_TRAIN_CANCELLED,
  FROM_START,
  IN_TRAIN,
  TO_BE_DEFINED_IN_SERVER,
  UNKNOWN,
}
