package de.jlnstrk.transit.client.hci.model.message

import de.jlnstrk.transit.client.hafas.HciModel
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@HciModel("1.45")
@Serializable
public enum class HciMessageTagType {
  RES_CON_FTR,
  @SerialName("RES_CON_FTR_H1")
  RES_CON_FTR_H_1,
  @SerialName("RES_CON_FTR_H2")
  RES_CON_FTR_H_2,
  @SerialName("RES_CON_FTR_H3")
  RES_CON_FTR_H_3,
  RES_CON_FTR_L,
  RES_CON_HDR,
  @SerialName("RES_CON_HDR_H1")
  RES_CON_HDR_H_1,
  @SerialName("RES_CON_HDR_H2")
  RES_CON_HDR_H_2,
  @SerialName("RES_CON_HDR_H3")
  RES_CON_HDR_H_3,
  RES_CON_HDR_L,
  RES_CON_PEARL_SEC_FTR_L,
  RES_CON_PEARL_SEC_HDR_L,
  RES_FLY_JNY,
  @SerialName("RES_FLY_JNY_H1")
  RES_FLY_JNY_H_1,
  @SerialName("RES_FLY_JNY_H2")
  RES_FLY_JNY_H_2,
  @SerialName("RES_FLY_JNY_H3")
  RES_FLY_JNY_H_3,
  RES_FLY_JNY_L,
  RES_FLY_LOC,
  @SerialName("RES_FLY_LOC_H1")
  RES_FLY_LOC_H_1,
  @SerialName("RES_FLY_LOC_H2")
  RES_FLY_LOC_H_2,
  @SerialName("RES_FLY_LOC_H3")
  RES_FLY_LOC_H_3,
  RES_FLY_LOC_L,
  RES_GEO_FLY_WEB,
  RES_GLB_FTR,
  @SerialName("RES_GLB_FTR_H1")
  RES_GLB_FTR_H_1,
  @SerialName("RES_GLB_FTR_H2")
  RES_GLB_FTR_H_2,
  @SerialName("RES_GLB_FTR_H3")
  RES_GLB_FTR_H_3,
  RES_GLB_FTR_L,
  RES_GLB_HDR,
  @SerialName("RES_GLB_HDR_H1")
  RES_GLB_HDR_H_1,
  @SerialName("RES_GLB_HDR_H2")
  RES_GLB_HDR_H_2,
  @SerialName("RES_GLB_HDR_H3")
  RES_GLB_HDR_H_3,
  RES_GLB_HDR_L,
  RES_JNY,
  RES_JNY_DTL,
  @SerialName("RES_JNY_DTL_H1")
  RES_JNY_DTL_H_1,
  @SerialName("RES_JNY_DTL_H2")
  RES_JNY_DTL_H_2,
  @SerialName("RES_JNY_DTL_H3")
  RES_JNY_DTL_H_3,
  RES_JNY_DTL_L,
  @SerialName("RES_JNY_H1")
  RES_JNY_H_1,
  @SerialName("RES_JNY_H2")
  RES_JNY_H_2,
  @SerialName("RES_JNY_H3")
  RES_JNY_H_3,
  RES_JNY_L,
  RES_LOC,
  RES_LOC_CAP_L,
  RES_LOC_DTL,
  @SerialName("RES_LOC_DTL_H1")
  RES_LOC_DTL_H_1,
  @SerialName("RES_LOC_DTL_H2")
  RES_LOC_DTL_H_2,
  @SerialName("RES_LOC_DTL_H3")
  RES_LOC_DTL_H_3,
  RES_LOC_DTL_L,
  RES_LOC_FLY_WEB,
  @SerialName("RES_LOC_H1")
  RES_LOC_H_1,
  @SerialName("RES_LOC_H2")
  RES_LOC_H_2,
  @SerialName("RES_LOC_H3")
  RES_LOC_H_3,
  RES_LOC_L,
  RES_LOC_WEB,
  RES_LOC_WEB_FTR,
  RES_LOC_WEB_HDR,
  RES_NAV,
  @SerialName("RES_NAV_H1")
  RES_NAV_H_1,
  @SerialName("RES_NAV_H2")
  RES_NAV_H_2,
  @SerialName("RES_NAV_H3")
  RES_NAV_H_3,
  RES_NAV_L,
  RES_PROD_FTR,
  @SerialName("RES_PROD_FTR_H1")
  RES_PROD_FTR_H_1,
  @SerialName("RES_PROD_FTR_H2")
  RES_PROD_FTR_H_2,
  @SerialName("RES_PROD_FTR_H3")
  RES_PROD_FTR_H_3,
  RES_PROD_FTR_L,
  RES_PROD_HDR,
  @SerialName("RES_PROD_HDR_H1")
  RES_PROD_HDR_H_1,
  @SerialName("RES_PROD_HDR_H2")
  RES_PROD_HDR_H_2,
  @SerialName("RES_PROD_HDR_H3")
  RES_PROD_HDR_H_3,
  RES_PROD_HDR_L,
  RES_PROD_ICON_L,
  RES_PUSH_L,
  RES_SEC_FTR,
  @SerialName("RES_SEC_FTR_H1")
  RES_SEC_FTR_H_1,
  @SerialName("RES_SEC_FTR_H2")
  RES_SEC_FTR_H_2,
  @SerialName("RES_SEC_FTR_H3")
  RES_SEC_FTR_H_3,
  RES_SEC_FTR_L,
  RES_SEC_HDR,
  @SerialName("RES_SEC_HDR_H1")
  RES_SEC_HDR_H_1,
  @SerialName("RES_SEC_HDR_H2")
  RES_SEC_HDR_H_2,
  @SerialName("RES_SEC_HDR_H3")
  RES_SEC_HDR_H_3,
  RES_SEC_HDR_L,
  RES_SEC_WEB,
  RES_SEC_WEB_FTR,
  RES_SEC_WEB_HDR,
  RES_STB,
  @SerialName("RES_STB_H1")
  RES_STB_H_1,
  @SerialName("RES_STB_H2")
  RES_STB_H_2,
  @SerialName("RES_STB_H3")
  RES_STB_H_3,
  RES_STB_L,
  RES_TRF_BOX_FTR,
  @SerialName("RES_TRF_BOX_FTR_H1")
  RES_TRF_BOX_FTR_H_1,
  @SerialName("RES_TRF_BOX_FTR_H2")
  RES_TRF_BOX_FTR_H_2,
  @SerialName("RES_TRF_BOX_FTR_H3")
  RES_TRF_BOX_FTR_H_3,
  RES_TRF_BOX_FTR_L,
  RES_TRF_BOX_HDR,
  @SerialName("RES_TRF_BOX_HDR_H1")
  RES_TRF_BOX_HDR_H_1,
  @SerialName("RES_TRF_BOX_HDR_H2")
  RES_TRF_BOX_HDR_H_2,
  @SerialName("RES_TRF_BOX_HDR_H3")
  RES_TRF_BOX_HDR_H_3,
  RES_TRF_BOX_HDR_L,
  RES_TRF_BOX_WEB_FTR,
  RES_TRF_BOX_WEB_HDR,
  RES_TRF_FARE_FTR,
  @SerialName("RES_TRF_FARE_FTR_H1")
  RES_TRF_FARE_FTR_H_1,
  @SerialName("RES_TRF_FARE_FTR_H2")
  RES_TRF_FARE_FTR_H_2,
  @SerialName("RES_TRF_FARE_FTR_H3")
  RES_TRF_FARE_FTR_H_3,
  RES_TRF_FARE_FTR_L,
  RES_TRF_FARE_HDR,
  @SerialName("RES_TRF_FARE_HDR_H1")
  RES_TRF_FARE_HDR_H_1,
  @SerialName("RES_TRF_FARE_HDR_H2")
  RES_TRF_FARE_HDR_H_2,
  @SerialName("RES_TRF_FARE_HDR_H3")
  RES_TRF_FARE_HDR_H_3,
  RES_TRF_FARE_HDR_L,
  RES_TRF_FARE_WEB_FTR,
  RES_TRF_FARE_WEB_HDR,
  RES_TRF_FSET_FTR,
  @SerialName("RES_TRF_FSET_FTR_H1")
  RES_TRF_FSET_FTR_H_1,
  @SerialName("RES_TRF_FSET_FTR_H2")
  RES_TRF_FSET_FTR_H_2,
  @SerialName("RES_TRF_FSET_FTR_H3")
  RES_TRF_FSET_FTR_H_3,
  RES_TRF_FSET_FTR_L,
  RES_TRF_FSET_HDR,
  @SerialName("RES_TRF_FSET_HDR_H1")
  RES_TRF_FSET_HDR_H_1,
  @SerialName("RES_TRF_FSET_HDR_H2")
  RES_TRF_FSET_HDR_H_2,
  @SerialName("RES_TRF_FSET_HDR_H3")
  RES_TRF_FSET_HDR_H_3,
  RES_TRF_FSET_HDR_L,
  RES_TRF_FSET_WEB_FTR,
  RES_TRF_FSET_WEB_HDR,
  RES_TRF_FTR,
  @SerialName("RES_TRF_FTR_H1")
  RES_TRF_FTR_H_1,
  @SerialName("RES_TRF_FTR_H2")
  RES_TRF_FTR_H_2,
  @SerialName("RES_TRF_FTR_H3")
  RES_TRF_FTR_H_3,
  RES_TRF_FTR_L,
  RES_TRF_HDR,
  @SerialName("RES_TRF_HDR_H1")
  RES_TRF_HDR_H_1,
  @SerialName("RES_TRF_HDR_H2")
  RES_TRF_HDR_H_2,
  @SerialName("RES_TRF_HDR_H3")
  RES_TRF_HDR_H_3,
  RES_TRF_HDR_L,
  RES_TRF_WEB_FTR,
  SUM_CLU_FTR,
  @SerialName("SUM_CLU_FTR_H1")
  SUM_CLU_FTR_H_1,
  @SerialName("SUM_CLU_FTR_H2")
  SUM_CLU_FTR_H_2,
  @SerialName("SUM_CLU_FTR_H3")
  SUM_CLU_FTR_H_3,
  SUM_CLU_FTR_L,
  SUM_CLU_HDR,
  @SerialName("SUM_CLU_HDR_H1")
  SUM_CLU_HDR_H_1,
  @SerialName("SUM_CLU_HDR_H2")
  SUM_CLU_HDR_H_2,
  @SerialName("SUM_CLU_HDR_H3")
  SUM_CLU_HDR_H_3,
  SUM_CLU_HDR_L,
  SUM_CON_CAP_L,
  SUM_CON_FTR,
  @SerialName("SUM_CON_FTR_H1")
  SUM_CON_FTR_H_1,
  @SerialName("SUM_CON_FTR_H2")
  SUM_CON_FTR_H_2,
  @SerialName("SUM_CON_FTR_H3")
  SUM_CON_FTR_H_3,
  SUM_CON_FTR_L,
  SUM_CON_HDR,
  @SerialName("SUM_CON_HDR_H1")
  SUM_CON_HDR_H_1,
  @SerialName("SUM_CON_HDR_H2")
  SUM_CON_HDR_H_2,
  @SerialName("SUM_CON_HDR_H3")
  SUM_CON_HDR_H_3,
  SUM_CON_HDR_L,
  SUM_CON_PEARL_SEC_FTR_L,
  SUM_CON_PEARL_SEC_HDR_L,
  SUM_GLB_FTR,
  @SerialName("SUM_GLB_FTR_H1")
  SUM_GLB_FTR_H_1,
  @SerialName("SUM_GLB_FTR_H2")
  SUM_GLB_FTR_H_2,
  @SerialName("SUM_GLB_FTR_H3")
  SUM_GLB_FTR_H_3,
  SUM_GLB_FTR_L,
  SUM_GLB_HDR,
  @SerialName("SUM_GLB_HDR_H1")
  SUM_GLB_HDR_H_1,
  @SerialName("SUM_GLB_HDR_H2")
  SUM_GLB_HDR_H_2,
  @SerialName("SUM_GLB_HDR_H3")
  SUM_GLB_HDR_H_3,
  SUM_GLB_HDR_L,
  SUM_HOME_CON_L,
  SUM_HOME_JNY_L,
  SUM_HOME_LOC_L,
  SUM_HOME_STB_L,
  SUM_JNY,
  @SerialName("SUM_JNY_H1")
  SUM_JNY_H_1,
  @SerialName("SUM_JNY_H2")
  SUM_JNY_H_2,
  @SerialName("SUM_JNY_H3")
  SUM_JNY_H_3,
  SUM_JNY_L,
  SUM_LOC,
  @SerialName("SUM_LOC_H1")
  SUM_LOC_H_1,
  @SerialName("SUM_LOC_H2")
  SUM_LOC_H_2,
  @SerialName("SUM_LOC_H3")
  SUM_LOC_H_3,
  SUM_LOC_L,
  SUM_PROD_ICON_L,
  SUM_SEC,
  @SerialName("SUM_SEC_H1")
  SUM_SEC_H_1,
  @SerialName("SUM_SEC_H2")
  SUM_SEC_H_2,
  @SerialName("SUM_SEC_H3")
  SUM_SEC_H_3,
  SUM_SEC_L,
  SUM_STB,
  @SerialName("SUM_STB_H1")
  SUM_STB_H_1,
  @SerialName("SUM_STB_H2")
  SUM_STB_H_2,
  @SerialName("SUM_STB_H3")
  SUM_STB_H_3,
  SUM_STB_L,
  SUM_SUB_CLU_FTR,
  @SerialName("SUM_SUB_CLU_FTR_H1")
  SUM_SUB_CLU_FTR_H_1,
  @SerialName("SUM_SUB_CLU_FTR_H2")
  SUM_SUB_CLU_FTR_H_2,
  @SerialName("SUM_SUB_CLU_FTR_H3")
  SUM_SUB_CLU_FTR_H_3,
  SUM_SUB_CLU_HDR,
  @SerialName("SUM_SUB_CLU_HDR_H1")
  SUM_SUB_CLU_HDR_H_1,
  @SerialName("SUM_SUB_CLU_HDR_H2")
  SUM_SUB_CLU_HDR_H_2,
  @SerialName("SUM_SUB_CLU_HDR_H3")
  SUM_SUB_CLU_HDR_H_3,
  SUM_TRF_BOX_FTR,
  @SerialName("SUM_TRF_BOX_FTR_H1")
  SUM_TRF_BOX_FTR_H_1,
  @SerialName("SUM_TRF_BOX_FTR_H2")
  SUM_TRF_BOX_FTR_H_2,
  @SerialName("SUM_TRF_BOX_FTR_H3")
  SUM_TRF_BOX_FTR_H_3,
  SUM_TRF_BOX_FTR_L,
  SUM_TRF_BOX_HDR,
  @SerialName("SUM_TRF_BOX_HDR_H1")
  SUM_TRF_BOX_HDR_H_1,
  @SerialName("SUM_TRF_BOX_HDR_H2")
  SUM_TRF_BOX_HDR_H_2,
  @SerialName("SUM_TRF_BOX_HDR_H3")
  SUM_TRF_BOX_HDR_H_3,
  SUM_TRF_BOX_HDR_L,
  SUM_TRF_BOX_WEB_FTR,
  SUM_TRF_BOX_WEB_HDR,
  SUM_TRF_FTR,
  @SerialName("SUM_TRF_FTR_H1")
  SUM_TRF_FTR_H_1,
  @SerialName("SUM_TRF_FTR_H2")
  SUM_TRF_FTR_H_2,
  @SerialName("SUM_TRF_FTR_H3")
  SUM_TRF_FTR_H_3,
  SUM_TRF_FTR_L,
  SUM_TRF_GROUP_FTR,
  @SerialName("SUM_TRF_GROUP_FTR_H1")
  SUM_TRF_GROUP_FTR_H_1,
  @SerialName("SUM_TRF_GROUP_FTR_H2")
  SUM_TRF_GROUP_FTR_H_2,
  @SerialName("SUM_TRF_GROUP_FTR_H3")
  SUM_TRF_GROUP_FTR_H_3,
  SUM_TRF_GROUP_HDR,
  @SerialName("SUM_TRF_GROUP_HDR_H1")
  SUM_TRF_GROUP_HDR_H_1,
  @SerialName("SUM_TRF_GROUP_HDR_H2")
  SUM_TRF_GROUP_HDR_H_2,
  @SerialName("SUM_TRF_GROUP_HDR_H3")
  SUM_TRF_GROUP_HDR_H_3,
  SUM_TRF_GROUP_WEB_FTR,
  SUM_TRF_GROUP_WEB_HDR,
  SUM_TRF_HDR,
  @SerialName("SUM_TRF_HDR_H1")
  SUM_TRF_HDR_H_1,
  @SerialName("SUM_TRF_HDR_H2")
  SUM_TRF_HDR_H_2,
  @SerialName("SUM_TRF_HDR_H3")
  SUM_TRF_HDR_H_3,
  SUM_TRF_HDR_L,
  SUM_TRF_WEB_HDR,
  UNDEF,
}
