name: "Run tests"

on:
  push:

jobs:
  tests:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Set test secrets
        env:
          TESTING_SECRETS: ${{ secrets.TESTING_SECRETS }}
        run: echo TESTING_SECRETS > ./secrets.properties

      - name: Assemble
        run: ./gradlew assemble

      - name: Tests
        run: ./gradlew check
